name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build project assets
        run: npm run build

  Test:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run E2E
        run: npm run e2e:headless

      - name: Saving the video
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress-videos
          path : cypress/videos