name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project assets
        run: npm run build

      - name: Run E2E
        run: npm run e2e:headless
