name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build project
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project assets
        run: npm run build


  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build project
        uses: actions/checkout@v3

      - name: Run E2E
        run: npm run e2e:headless

      - name: Saving the video
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress-videos
          path : cypress/videos