name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: E2E tests
        run: |
          npm run e2e
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress-videos
          path: cypress/videos