name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
