name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: Initiliaze cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Cache recovery
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run E2E
        run: |
          npm run e2e:headless

      - name: Saving video
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress-videos
          path : cypress/videos
  build-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tilefevre/my-cypress-app/nodejs-my-website:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull ghcr.io/tilefevre/my-cypress-app/nodejs-my-website:latest
            docker run -d -p 3000:3000 ghcr.io/tilefevre/my-cypress-app/nodejs-my-website
            

 
