name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: E2E tests
        run: |
          npm run e2e
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-tests
          path: cypress/videos