name: build-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        uses: actions/checkout@v3

      - name: Initiliaze cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Cache recovery
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Run E2E
        run: |
          npm run e2e:headless

      - name: Saving video
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: cypress-videos
          path : cypress/videos