name: deploy-github-actions
run-name: Build by -> ${{ github.actor }}
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd my-cypress-app
          git pull
          npm install
          npm run build
          pm2 restart all
